import Head from "next/head";
import { Inter } from "next/font/google";
import BoardListItem from "@/components/BoardListItem";
import {
  commentListMock,
  favoriteListMock,
  latestBoardListMock,
  latestTop3ListMock,
} from "@/mocks";
import Top3Item from "@/components/Top3Item";
import CommentItem from "@/components/CommentItem";
import FavoriteItem from "@/components/FavoriteItem";
import MainLayout from "@/layouts/Layout/MainLayout/MainLayout";
import style from "./style.module.scss";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <MainLayout path="home">
        <div className={style["main-wrapper"]}>
          <div className={style["main-container"]}>
            {latestBoardListMock.map((boardListItem) => (
              <BoardListItem
                key={boardListItem.boardNumber}
                boardListItem={boardListItem}
              />
            ))}
            <div
              className={style['top3-list']}
            >
              {latestTop3ListMock.map((top3ListItem) => (
                <Top3Item
                  key={top3ListItem.boardNumber}
                  top3ListItem={top3ListItem}
                />
              ))}
            </div>

            <div
              style={{ display: "flex", flexDirection: "column", gap: "30px" }}
            >
              {commentListMock.map((commentItem, idx) => (
                <CommentItem
                  key={`${commentItem.nickname}-${idx}`}
                  commentItem={commentItem}
                />
              ))}
            </div> 

            <div
              style={{ display: "flex", flexDirection: "column", gap: "30px" }}
            >
              {favoriteListMock.map((favoriteItem, idx) => (
                <FavoriteItem
                  key={`${favoriteItem.nickname}-${idx}`}
                  favoriteItem={favoriteItem}
                />
              ))}
            </div>
          </div>
        </div>
      </MainLayout>
    </>
  );
}
