enum ResponseCode{
  // HTTP STATUS 200
   SUCCESS = "SU",
  
  // HTTP STATUS 400
   VALIDATION_FAILED ="VF",
   DUPLICATION_EMAIL ="DE",
   DUPLICATION_NICKNAME ="DN",
   DUPLICATION_TEL_NUMBER ="DT",
   NOT_EXISTED_USER ="NU",
   NOT_EXISTED_BORAD ="NB",
  
  // HTTP STATUS 401
   SIGN_IN_FAIL ="SF",
   AUTHORIZATION_FAIL ="AF",

  // HTTP STATUS 403
   NO_PERMISSION ="NP",

  // HTTP STATUS 500
   DATABASE_ERROR ="DBE",

}

export default ResponseCode